#!/usr/bin/env python3
"""
IRIB Live Channels Extractor with EPG
by @kgkaku
"""

import json
import requests
from datetime import datetime
import xml.etree.ElementTree as ET
from xml.dom import minidom

CHANNEL_LIST_URL = "https://gateway.telewebion.ir/kandoo/channel/getChannelsList/?NumOfItems=300&v=4.4.1"
CHANNEL_DETAILS_URL = "https://gateway.telewebion.ir/kandoo/v3/channel/getChannelDetails/?Descriptor={}"
EPISODES_URL = "https://gateway.telewebion.ir/kandoo/channel/getChannelEpisodesByDate/?ChannelDescriptor={}&FromDate={}T00:00:00&ToDate={}T23:59:59&IsClip=false&First=50&Offset=0"
STREAM_BASE_URL = "https://ncdn.telewebion.ir/{}/live/playlist.m3u8"
LOGO_BASE_URL = "https://static.telewebion.ir/channelsLogo/{}/default"

HEADERS = {
    "User-Agent": "Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36",
    "Accept": "application/json, text/plain, */*",
    "Origin": "https://telewebion.ir",
    "Referer": "https://telewebion.ir/"
}

GROUP_MAP = {
    "national": "National",
    "provincial": "Provincial",
    "exclusive": "Exclusive",
    "international": "International",
    "radio": "Radio"
}

def fetch_channels():
    response = requests.get(CHANNEL_LIST_URL, headers=HEADERS, timeout=30)
    response.raise_for_status()
    data = response.json()
    return data.get("body", {}).get("queryChannel", [])

def fetch_channel_details(descriptor):
    try:
        url = CHANNEL_DETAILS_URL.format(descriptor)
        response = requests.get(url, headers=HEADERS, timeout=30)
        response.raise_for_status()
        data = response.json()
        channels = data.get("body", {}).get("queryChannel", [])
        return channels[0] if channels else None
    except:
        return None

def fetch_episodes(descriptor, date):
    try:
        url = EPISODES_URL.format(descriptor, date, date)
        response = requests.get(url, headers=HEADERS, timeout=30)
        response.raise_for_status()
        data = response.json()
        channels = data.get("body", {}).get("queryChannel", [])
        if channels:
            return channels[0].get("episodes", [])
        return []
    except:
        return []

def get_logo_url(image_name):
    if not image_name:
        return ""
    return LOGO_BASE_URL.format(image_name)

def get_group_name(channel_type):
    if isinstance(channel_type, dict):
        descriptor = channel_type.get("descriptor", "national")
    else:
        descriptor = "national"
    return GROUP_MAP.get(descriptor, "General")

def generate_epg_xml(channels, date):
    tv = ET.Element("tv")
    tv.set("generator-info-name", "IRIB Extractor by @kgkaku")
    tv.set("date", date)
    
    for ch in channels:
        descriptor = ch.get("descriptor")
        name_en = ch.get("name_english", descriptor)
        
        channel_elem = ET.SubElement(tv, "channel")
        channel_elem.set("id", descriptor)
        
        display_name = ET.SubElement(channel_elem, "display-name")
        display_name.text = name_en
        
        episodes = fetch_episodes(descriptor, date)
        
        for ep in episodes:
            program = ep.get("program", {})
            prog_title = program.get("title", ep.get("title", "No Title"))
            ep_title = ep.get("title", prog_title)
            started_at = ep.get("started_at")
            ended_at = ep.get("ended_at")
            duration = ep.get("duration", 0)
            
            if not started_at or not ended_at:
                continue
            
            try:
                start_dt = datetime.fromisoformat(started_at.replace('Z', '+00:00'))
                end_dt = datetime.fromisoformat(ended_at.replace('Z', '+00:00'))
                
                programme = ET.SubElement(tv, "programme")
                programme.set("start", start_dt.strftime("%Y%m%d%H%M%S +0000"))
                programme.set("stop", end_dt.strftime("%Y%m%d%H%M%S +0000"))
                programme.set("channel", descriptor)
                
                title_elem = ET.SubElement(programme, "title")
                title_elem.text = ep_title
                
                if prog_title and prog_title != ep_title:
                    sub_title = ET.SubElement(programme, "sub-title")
                    sub_title.text = prog_title
                
                if duration:
                    length = ET.SubElement(programme, "length")
                    length.set("units", "seconds")
                    length.text = str(duration)
            except Exception as e:
                continue
    
    rough_string = ET.tostring(tv, encoding="utf-8")
    reparsed = minidom.parseString(rough_string)
    return reparsed.toprettyxml(indent="  ", encoding="utf-8").decode("utf-8")

def generate_simple_m3u(channels, epg_url=""):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    m3u_lines = ['#EXTM3U', f'# Generated by @kgkaku - {timestamp}', '']
    
    if epg_url:
        m3u_lines.append(f'#EXTM3U url-tvg="{epg_url}"')
    
    for ch in channels:
        descriptor = ch.get("descriptor")
        name_en = ch.get("name_english", descriptor)
        name_fa = ch.get("name", descriptor)
        image_name = ch.get("image_name", "")
        group = get_group_name(ch.get("type", {}))
        
        stream_url = STREAM_BASE_URL.format(descriptor)
        logo_url = get_logo_url(image_name)
        
        extinf = f'#EXTINF:-1 tvg-id="{descriptor}" tvg-name="{name_fa}" tvg-logo="{logo_url}" group-title="{group}",{name_en}'
        m3u_lines.append(extinf)
        m3u_lines.append(stream_url)
        m3u_lines.append('')
    
    return '\n'.join(m3u_lines)

def generate_extvlcopt_m3u(channels, epg_url=""):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    m3u_lines = ['#EXTM3U', f'# Generated by @kgkaku - {timestamp}', '']
    
    if epg_url:
        m3u_lines.append(f'#EXTM3U url-tvg="{epg_url}"')
    
    for ch in channels:
        descriptor = ch.get("descriptor")
        name_en = ch.get("name_english", descriptor)
        name_fa = ch.get("name", descriptor)
        image_name = ch.get("image_name", "")
        group = get_group_name(ch.get("type", {}))
        
        stream_url = STREAM_BASE_URL.format(descriptor)
        logo_url = get_logo_url(image_name)
        
        extinf = f'#EXTINF:-1 tvg-id="{descriptor}" tvg-name="{name_fa}" tvg-logo="{logo_url}" group-title="{group}",{name_en}'
        m3u_lines.append(extinf)
        m3u_lines.append('#EXTVLCOPT:http-referrer=https://telewebion.ir/')
        m3u_lines.append('#EXTVLCOPT:http-user-agent=Mozilla/5.0 (Linux; Android 10; K) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/132.0.0.0 Mobile Safari/537.36')
        
        details = fetch_channel_details(descriptor)
        if details and details.get("channel_token"):
            m3u_lines.append(f'#EXTVLCOPT:http-header=Authorization: Bearer {details["channel_token"]}')
        
        m3u_lines.append(stream_url)
        m3u_lines.append('')
    
    return '\n'.join(m3u_lines)

def generate_json_output(channels):
    output = {
        "generated": datetime.now().isoformat(),
        "credit": "@kgkaku",
        "total_channels": len(channels),
        "channels": []
    }
    
    for ch in channels:
        image_name = ch.get("image_name", "")
        
        ch_info = {
            "descriptor": ch.get("descriptor"),
            "name_fa": ch.get("name"),
            "name_en": ch.get("name_english"),
            "type": ch.get("type", {}).get("name"),
            "type_descriptor": ch.get("type", {}).get("descriptor"),
            "group_name_en": get_group_name(ch.get("type")),
            "has_archive": ch.get("has_archive", False),
            "priority": ch.get("priority"),
            "logo_url": get_logo_url(image_name),
            "stream_url": STREAM_BASE_URL.format(ch.get("descriptor")),
            "channel_id": ch.get("ChannelID")
        }
        
        details = fetch_channel_details(ch.get("descriptor"))
        if details:
            ch_info["channel_token"] = details.get("channel_token")
            ch_info["epg_code"] = details.get("epg_code")
        
        output["channels"].append(ch_info)
    
    return output

def main():
    print("=" * 50)
    print("IRIB Live Channels Extractor with EPG")
    print("by @kgkaku")
    print(f"Started: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 50)
    
    channels = fetch_channels()
    if not channels:
        print("Error: No channels found!")
        return
    
    print(f"Success: {len(channels)} channels found")
    
    type_count = {}
    for ch in channels:
        t = ch.get("type", {}).get("descriptor", "unknown")
        type_count[t] = type_count.get(t, 0) + 1
    
    print("\nChannel types:")
    for t, count in type_count.items():
        print(f"  - {t}: {count}")
    
    # Generate EPG XML
    today = datetime.now().strftime("%Y-%m-%d")
    print(f"\nGenerating EPG XML for {today}...")
    
    epg_xml = generate_epg_xml(channels, today)
    with open("epg.xml", "w", encoding="utf-8") as f:
        f.write(epg_xml)
    print("Success: epg.xml")
    
    # Generate Simple M3U
    print("\nGenerating Simple M3U...")
    with open("irib_simple.m3u", "w", encoding="utf-8") as f:
        f.write(generate_simple_m3u(channels, epg_url="epg.xml"))
    print("Success: irib_simple.m3u")
    
    # Generate Extvlcopt M3U
    print("\nGenerating Extvlcopt M3U...")
    with open("irib_extvlcopt.m3u", "w", encoding="utf-8") as f:
        f.write(generate_extvlcopt_m3u(channels, epg_url="epg.xml"))
    print("Success: irib_extvlcopt.m3u")
    
    # Generate JSON
    print("\nGenerating JSON...")
    with open("irib.json", "w", encoding="utf-8") as f:
        json.dump(generate_json_output(channels), f, ensure_ascii=False, indent=2)
    print("Success: irib.json")
    
    print("\n" + "=" * 50)
    print(f"Done! Total: {len(channels)} channels")
    print("Files: irib_simple.m3u, irib_extvlcopt.m3u, irib.json, epg.xml")
    print("=" * 50)

if __name__ == "__main__":
    main()
